projects:
  tetris:
    schemaPath: amplify/backend/api/tetris/build/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphql/API.ts
        docsFilePath: graphql
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
